name: Deploy & Build
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # clone
      - name: Checkout
        uses: actions/checkout@master

      # deploy
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NANJING2 }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /www/wwwroot/jx3box/jx3box-v2/data
            cd analysis-dungeon-rank
            git pull origin main
      # - name: node
      #   run: |
      #     npm install
      #     npm run build
